---
- name: Install Apache Packages on RedHat Nodes
  yum: name=httpd state=present
  when: ansible_os_family == "RedHat"
- name: Install Apache Packages on Ubuntu Nodes
  apt: name=apache2 state=present
  when: ansible_os_family == "debain"
- name: Start Apache Service
  service: name=httpd state=started enabled=true
- name: Create Site Location
  file: path={{doc_root}} state=directory
- name: Deploy Sample Sites Files
  template: src=templates/index.j2 dest={{doc_root}}/index.html
  notify:
  - nothing
- name: Deploy Sample Sites Files
  template: src=templates/info.j2 dest={{doc_root}}/info.html
- debug: msg="Username is varible prompt is{{username}}"
