---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-a5b196c0
    instance_type: t2.micro
    vpc_subnet_id: subnet-6456fd1f
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: aws-ec2
verifier:
  name: testinfra
  lint:
    name: flake8
